### ISSUE TITLE
License of certain files

### ISSUE THREAD

**Issue by Garbee** [Gixx/mdl-kvl#1]
You seem to have [removed the license](https://github.com/Gixx/mdl-components-ext/commit/f29897f164e2ac166d1dbbfd2814faf84ce0ef7b#diff-25f59fc980ec10b2b6a89d30511c363f) on a few files in your repository. This is clearly _against_ the license provided. [Apache license 2.0](http://www.apache.org/licenses/LICENSE-2.0)  Section 4, like in whole is violated here.

It would be great if the open source community could adhere to the licenses other things they use are provided under. Otherwise, the licenses don't really mean anything.

Thanks for understanding.
- Garbee

**Comment by Gixx** [comment]
Hi,

Thank you for paying my attention on my mistake. When the project was in only in development phase, I removed those license to make the development overview clearer (I was needn't to scroll through the licenses again and again) and somehow I've just forget about them later when I used the YUI compressor, which removes every comment anyways.

But now I refactored the sources a little bit and placed the whole [Material Design Lite](https://github.com/google/material-design-lite) into the vendor folder untouched and also placed a LICENSE-MDL in the project root.

Please check and alert me whenever you find any license-breaking more. It's the open source community that makes the World go round :)

I honestly apologize for the inconvenience. 

Best regards,
Gabor Ivan

**Comment by Garbee** [comment]
Well, you don't need `license-mdl` at all since you are no longer copying our files in directly. Since you reference ours via a package manager, it is automatically included when that is pulled.

The problem is absolutely resolved with this though, so closing it on out. Thanks so much!
