### ISSUE TITLE
Clearing an input element makes it not changeable.

### ISSUE THREAD

**Issue by ghost** [Gixx/mdl-kvl#12]
I use this line of code to clear the text input field generated by your library around a file input field:

`inputFields.value = ''`

And after applying this code the input field doesn't change anymore when I choose a file. Its value changes, but not visually.
How to correctly clear this field using your library?

**Comment by Gixx** [comment]
Hi, 

sorry for the very late reply. I made some update in the package and added support to reset the file upload field:

* Now the default Form reset button (event) is supported.
* You can use this code (experimental): ```componentRegister.getComponentById('myFileInputElement').resetInput_();```

Please update your package to 1.7.0 or download it from the [https://github.com/Gixx/mdl-components-ext/tree/master/package](package) folder.

_Note: the demo website will be updated later..._

**Comment by ghost** [comment]
Thank you very much for the update!
