### ISSUE TITLE
Wrong material-design-lite version

### ISSUE THREAD

**Issue by hersonls** [Gixx/mdl-kvl#13]
Hi, I tried to use your library and I saw you set version 3.0.0 in material-design-lite dependence in package.json. I made some researches and don't saw any material-design-lite package in NPM with this version.

So I made a PR with the latest version 1.3.0.

Can you confirm if is really wrong or if is another package that I can't saw?

**Comment by Gixx** [comment]
OMG, great catch, thank you! 
Merged, published (the badge might remain cached by github for a while).
