### ISSUE TITLE
online examples of mdl-components-ext

### ISSUE THREAD

**Issue by SabineMa** [Gixx/mdl-kvl#2]
Hi,
mdl-components-ext sounds interesting for me. Do you have mdl-components-ext running online somewhere to get an impression of it?
Regards
Sabine

**Comment by Gixx** [comment]
Hi Sabine,

Thanks for writing. As soon as I get home from work today, I'll prepare a demo from the snippets.

Best,
Gabor

**Comment by Gixx** [comment]
Hi Sabine,

Sorry for the late answer, I had to rebuild my whole development enviroment, and also wanted to create a better demo page then just a html file.

Here's the demo page: http://mdl.gixx-web.com/

Best,
Gabor

**Comment by SabineMa** [comment]
Hi Gabor,
Thank you! I am in holidays. When I am back, I will have a look at it.
Sabine

Am Dienstag, 2. Februar 2016 schrieb Gabor Ivan :
