### ISSUE TITLE
File input console error

### ISSUE THREAD

**Issue by LipeDuoli** [Gixx/mdl-kvl#3]
I trying to use the input file but I getting this erro on console:

`material.components.ext.min.js:9 Uncaught ReferenceError: componentHandler is not defined`

test on v1.4

**Comment by LipeDuoli** [comment]
Sorry, my bad
I download the material.js insted use link from CDN and now everything work fine.

**Comment by Gixx** [comment]
Sorry, I didn't get the notification in time :( 

But I'm glad you could solve the issue and it's working now :)
