### ISSUE TITLE
Avatar component doesn't display on some mobile devices

### ISSUE THREAD

**Issue by ProMcTagonist** [Gixx/mdl-kvl#4]
I've tested with:

Safari on iOS 8 on an iPhone 4S

Firefox on iOS 8 on an iPhone 4S

Safari on iOS 9 on an iPhone 6+

Chrome on iOS 9 on an iPhone 6+

Chrome 48.0.2 on Android 5.0.2

On both iPhones it never appears at all, leaving a large blank square on both my site and your demo site.

On the Android device it appears about 30% of the time, judged from many refreshes and fresh page loads on my site, and more often on your demo site.

Has anyone else experienced this?

**Comment by Gixx** [comment]
Hi, 

Thanks for the testing and reporting. Unfortunately I can test only on my 4-year-old phone (Android 4.1.2) and on PC (Windows 10). I can also test it in my workplace (OSX El Capitan). Treu, in OSX Safari it doesn't work, I'll check the debugger, but the Firefox (46.0.1) works well.

If anybody can help me identifying the errors and/or provide solutions by pull request, I'd appreciate it.

Thanks

**Comment by Gixx** [comment]
Hi again, 

I think I found the error. At least now it works on OSX Safari. Hopefully it also fixed the iPhone issues.
It was a JS query selector that the Safari parsed with syntax error.

Unfortunately I don't have access to my demo website right now, but the sources are updated on Github.

You can download the fixed package from the demo branch: https://github.com/Gixx/mdl-components-ext/tree/branches/demo/package

Can you please use this and test again?

Thanks,
Gabor

**Comment by ProMcTagonist** [comment]
I'm using the updated version you linked and it doesn't seem to have changed anything. 

Same results as before.

**Comment by Gixx** [comment]
Hi, 

I'm terribly sorry, it's my fault. I forgot to update the ZIP file :D Now it's okay. You can surely download it from the demo site which is also updated now: http://mdl.gixx-web.dev/getting-started.html

You should see the `@version   1.6.3` in the JS file.

**Comment by ProMcTagonist** [comment]
It's working every time now on iOS! 

On the Android device it's now working about half of the time, ~every other time I refresh. But the one on your site works perfectly so it must be a misconfiguration on my end.

Thanks for the quick responses and help.
