### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by arabsight** [Gixx/mdl-kvl#7]
would you consider publishing to npm.

**Comment by Gixx** [comment]
Good idea. Don't know how to do that yet, but will figure it out ;)

But earliest next year after the vacation :)

**Comment by arabsight** [comment]
OK, thanks.

**Comment by Gixx** [comment]
Hi,

I'll be honest: I have no clue how should a npm package look like, I followed the documentation and some public packages, but it's a bit chaotic to me. So the package is here (the README is outdated, don't know when and how to make it up-to-date):

https://www.npmjs.com/package/mdl-components-ext

I still recommend to simply download the JS and CSS files from the ```package``` folder without the whole surrounding sources which you will never need.

Or if you are more into this NPM thingy, could you please fix/update/create a proper package.json which works as expected? 

I'm a PHP guy, I work with composer you know ;)

**Comment by arabsight** [comment]
Hi, it's working, the readme is the same, the package.json is good. thank you.
to release a new version just change the version in package.json and run *npm publish*
