### ISSUE TITLE
componentHandler is not defined

### ISSUE THREAD

**Issue by chase-bleyl** [Gixx/mdl-kvl#8]
I am receiving an error, `Uncaught ReferenceError: componentHandler is not defined`. I pulled the two minified files out of the download folder off your website. I saw another issue with the same problem (#3) but I couldn't figure out if that user used a CDN to resolve his issue, and if so, where he got that CDN from.

Any and all help greatly appreciated.

**Comment by Gixx** [comment]
Hi,

Did you also use the official MDL? My lib is an extension and not a fork.

Please check my website for details:
http://mdl.gixx-web.com/getting-started.html

Best,
Gabor "Gixx" Ivan

2017. jan. 12. 19:51 ezt írta ("Chase Bleyl" <notifications@github.com>):

**Comment by chase-bleyl** [comment]
I went with another solution. Thank you for responding.
